language: c

env:
  matrix:
    - VALA=vala-0.24

install:
  - if [ "$VALA" = "vala-0.24" ]; then
      sudo add-apt-repository -y ppa:vala-team &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq autotools-dev gobject-introspection intltool libgee-0.8-dev libgirepository1.0-dev libjson-glib-dev "$VALA";
    fi

script:
  ./autogen.sh && make && make check
