name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  INSTALLDIR: "installdir"
  RUNUSER: "user"
  PROFILE: "testable"

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: --enable-docs --disable-fep
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-autotools

  asan:
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: --disable-fep
      CFLAGS: -fsanitize=address -g -fno-common -U_FORTIFY_SOURCE
      CXXFLAGS: -fsanitize=address -g -fno-common -U_FORTIFY_SOURCE
      LDFLAGS: -fsanitize=address -g -fno-common -U_FORTIFY_SOURCE
      LIBS: -ldl -lpthread
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-autotools

  ubsan:
    runs-on: ubuntu-latest
    env:
      BUILD_OPTS: --disable-fep
      CFLAGS: -fsanitize=undefined -g -fno-common -U_FORTIFY_SOURCE
      CXXFLAGS: -fsanitize=undefined -g -fno-common -U_FORTIFY_SOURCE
      LDFLAGS: -fsanitize=undefined -g -fno-common -U_FORTIFY_SOURCE
      LIBS: -ldl -lpthread
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-autotools
